### ISSUE TITLE
Search Element in Linked List

### ISSUE THREAD

**Issue by G1Joshi** [C0D1NG/Data-Structures#10]
## Write a program to search an element in a linked list.

This **issue** is open for all, so everyone can work on this issue and every valid **pull request** will be merged.
Maximum number of people can work on this issue, there is no limitations.

### 👨🏻‍💻 Happy Coding 👩🏻‍💻

**Comment by arynn-gupta** [comment]
Would definitely like to work on this issue !

**Comment by amaan-ahmad** [comment]
@G1Joshi Completed! Check Pull request #42

**Comment by yashica-patodia** [comment]
I want to work on this issue @G1Joshi

**Comment by arynn-gupta** [comment]
Given solution in C++ . Pease merge  https://github.com/C0D1NG/Data-Structures/pull/71

**Comment by HANS-2002** [comment]
@G1Joshi please check PR #293 and merge if suitable.

**Comment by Rohan-2107** [comment]
@G1Joshi please review my PR #302.
