### ISSUE TITLE
Insertion in Sorted Linked List

### ISSUE THREAD

**Issue by G1Joshi** [C0D1NG/Data-Structures#11]
## Write a program to insert an element in sorted linked list.

This **issue** is open for all, so everyone can work on this issue and every valid **pull request** will be merged.
Maximum number of people can work on this issue, there is no limitations.

### 👨🏻‍💻 Happy Coding 👩🏻‍💻

**Comment by arynn-gupta** [comment]
Would definitely like to work on this issue !

**Comment by yashica-patodia** [comment]
I want to work on this issue @G1Joshi

**Comment by kavyasritulabandu** [comment]
> 
> ## Write a program to insert an element in sorted linked list.
> 
> This **issue** is open for all, so everyone can work on this issue and every valid **pull request** will be merged.
> Maximum number of people can work on this issue, there is no limitations.
> ## File format 👉🏻 username_filename.extention
> ### 👨🏻‍💻 Happy Coding
I've done this in python. Kindly review [#114](https://github.com/C0D1NG/Data-Structures/pull/114)

**Comment by Rit7knight** [comment]
I would also love to work on it.

**Comment by arynn-gupta** [comment]
Given solution in C++ . Pease merge  https://github.com/C0D1NG/Data-Structures/pull/68

**Comment by thecoderash** [comment]
@G1Joshi please review my PR #297
