### ISSUE TITLE
Sum of Array Elements

### ISSUE THREAD

**Issue by ManojChandraJoshi** [C0D1NG/Data-Structures#112]

**Comment by devmohit-live** [comment]
I would like to take this issue.

**Comment by deepadhia** [comment]
I would love to Commit

**Comment by rakshathavasudev** [comment]
Would like to contribute to this issue.

**Comment by Rit7knight** [comment]
I  would also like to contribute

**Comment by nitya09m** [comment]
I would like to contribute to this issue
