### ISSUE TITLE
Infix to Postfix Conversion

### ISSUE THREAD

**Issue by G1Joshi** [C0D1NG/Data-Structures#13]
## Write a program to convert infix expression into postfix expression.

This **issue** is open for all, so everyone can work on this issue and every valid **pull request** will be merged.
Maximum number of people can work on this issue, there is no limitations.

### 👨🏻‍💻 Happy Coding 👩🏻‍💻

**Comment by arynn-gupta** [comment]
Would definitely like to work on this issue !

**Comment by KshitijDarekar** [comment]
Hi @G1Joshi , would like to contribute the code in C language.

**Comment by arynn-gupta** [comment]
Given solution in C++ . Pease merge  https://github.com/C0D1NG/Data-Structures/pull/58
