### ISSUE TITLE
Infix to Prefix Conversion

### ISSUE THREAD

**Issue by G1Joshi** [C0D1NG/Data-Structures#14]
## Write a program to convert infix expression into prefix expression.

This **issue** is open for all, so everyone can work on this issue and every valid **pull request** will be merged.
Maximum number of people can work on this issue, there is no limitations.

### 👨🏻‍💻 Happy Coding 👩🏻‍💻

**Comment by AkshadK7** [comment]
Can I be assigned this issue for a HacktoberFest PR ?

**Comment by arynn-gupta** [comment]
Would definitely like to work on this issue !

**Comment by arynn-gupta** [comment]
Given solution in C++ . Pease merge https://github.com/C0D1NG/Data-Structures/pull/61
