### ISSUE TITLE
Reverse a Queue

### ISSUE THREAD

**Issue by G1Joshi** [C0D1NG/Data-Structures#16]
## Write a program to reverse a queue.

This **issue** is open for all, so everyone can work on this issue and every valid **pull request** will be merged.
Maximum number of people can work on this issue, there is no limitations.

### 👨🏻‍💻 Happy Coding 👩🏻‍💻

**Comment by chicken-biryani** [comment]
Can I work on these with python?

**Comment by amaan-ahmad** [comment]
@G1Joshi  I completed this using CPP, kindly check my pull request, please.

**Comment by chicken-biryani** [comment]
I have worked on this issue, language-python

**Comment by adityarajbhagat2002** [comment]
Please review my PR #285 and merge if suitable.
