### ISSUE TITLE
Circular Queue using Linked Lists

### ISSUE THREAD

**Issue by G1Joshi** [C0D1NG/Data-Structures#18]
## Write a program to implement circular queue using linked list.

This **issue** is open for all, so everyone can work on this issue and every valid **pull request** will be merged.
Maximum number of people can work on this issue, there is no limitations.

### 👨🏻‍💻 Happy Coding 👩🏻‍💻

**Comment by sb2356-iiitr** [comment]
Can I work on this, if you may? @G1Joshi

**Comment by Parshwa52** [comment]
Can I work on this issue?

**Comment by sb2356-iiitr** [comment]
I have made a pull request @G1Joshi please check it

**Comment by rishika-singh49** [comment]
Can I work on this issue?
