### ISSUE TITLE
Palindrome String

### ISSUE THREAD

**Issue by G1Joshi** [C0D1NG/Data-Structures#2]
## Write a program to check if the given string is Palindrome or not

Maximum number of people can work on this issue there is no limits, make sure that the each filename should also contain your ```username``` to avoid merge conflicts and overriding.

### 👨🏻‍💻 Happy Coding 👩🏻‍💻

**Comment by cBridges851** [comment]
Hi! Does it matter how the string is given in - i.e. via a command-line argument or an input inside the program itself? Thanks.

**Comment by cBridges851** [comment]
Also, which folder will the program go in?

**Comment by G1Joshi** [comment]
This program belongs to string folder.
@cBridges851 try to provide the input in program itself.

**Comment by GC2002** [comment]
hi! can i contribute?

**Comment by syk007** [comment]
Hi, Adding code in Python

**Comment by syk007** [comment]
Hi, Can I do it in R?

**Comment by syk007** [comment]
Done. Review and merge #206
