### ISSUE TITLE
Preorder Tree Traversal

### ISSUE THREAD

**Issue by G1Joshi** [C0D1NG/Data-Structures#20]
## Write a program to implement preorder tree traversal.

This **issue** is open for all, so everyone can work on this issue and every valid **pull request** will be merged.
Maximum number of people can work on this issue, there is no limitations.

### 👨🏻‍💻 Happy Coding 👩🏻‍💻

**Comment by arynn-gupta** [comment]
Would definitely like to work on this issue !

**Comment by yashica-patodia** [comment]
I want to work on this issue

**Comment by pawki07** [comment]
Hey, I would like to contribute to this issue.

**Comment by rakshathavasudev** [comment]
Hey!I would like to contribute to this issue

**Comment by pawki07** [comment]
Hey, I would like to work on this issue. Please assign it to me.

**Comment by arynn-gupta** [comment]
Given solution in C++ . Pease merge https://github.com/C0D1NG/Data-Structures/pull/76

**Comment by adityarajbhagat2002** [comment]
@G1Joshi  please review PR #286 and merge if suitable.
