### ISSUE TITLE
Postorder Tree Traversal

### ISSUE THREAD

**Issue by G1Joshi** [C0D1NG/Data-Structures#21]
## Write a program to implement postorder tree traversal.

This **issue** is open for all, so everyone can work on this issue and every valid **pull request** will be merged.
Maximum number of people can work on this issue, there is no limitations.

### 👨🏻‍💻 Happy Coding 👩🏻‍💻

**Comment by arynn-gupta** [comment]
Would definitely like to work on this issue !

**Comment by arynn-gupta** [comment]
Given solution in C++ . Pease merge  https://github.com/C0D1NG/Data-Structures/pull/75

**Comment by priyalgupta09** [comment]
hey! can i work on this . i will make program without recursion in c

**Comment by adityarajbhagat2002** [comment]
@G1Joshi please review PR #286 and merge if suitable.

**Comment by adityarajbhagat2002** [comment]
@G1Joshi please review my PR #287  and merge if suitable.
