### ISSUE TITLE
Search in Binary Search Tree

### ISSUE THREAD

**Issue by G1Joshi** [C0D1NG/Data-Structures#22]
## Write a program to search an element in binary search tree.

This **issue** is open for all, so everyone can work on this issue and every valid **pull request** will be merged.
Maximum number of people can work on this issue, there is no limitations.

### 👨🏻‍💻 Happy Coding 👩🏻‍💻

**Comment by AkshadK7** [comment]
Can I be assigned this task for a HacktoberFest PR ?

**Comment by yashica-patodia** [comment]
I want to work on this issue

**Comment by priyalgupta09** [comment]
hey! can i work on this in c.
Thank you
