### ISSUE TITLE
Breadth First Search (BFS)

### ISSUE THREAD

**Issue by G1Joshi** [C0D1NG/Data-Structures#23]
## Write a program to implement breadth first search in trees.

This **issue** is open for all, so everyone can work on this issue and every valid **pull request** will be merged.
Maximum number of people can work on this issue, there is no limitations.

### 👨🏻‍💻 Happy Coding 👩🏻‍💻

**Comment by arynn-gupta** [comment]
Would definitely like to work on this issue !

**Comment by HANS-2002** [comment]
@G1Joshi please review PR #283 and merge if suitable.
