### ISSUE TITLE
Depth First Search (DFS)

### ISSUE THREAD

**Issue by G1Joshi** [C0D1NG/Data-Structures#24]
## Write a program to implement depth first search in trees.

This **issue** is open for all, so everyone can work on this issue and every valid **pull request** will be merged.
Maximum number of people can work on this issue, there is no limitations.

### 👨🏻‍💻 Happy Coding 👩🏻‍💻

**Comment by arynn-gupta** [comment]
Would definitely like to work on this issue !

**Comment by arynn-gupta** [comment]
Given solution in C++ . Pease merge https://github.com/C0D1NG/Data-Structures/pull/56

**Comment by HANS-2002** [comment]
@G1Joshi please review PR #282 and merge if suitable.
