### ISSUE TITLE
Size of the Binary Tree

### ISSUE THREAD

**Issue by G1Joshi** [C0D1NG/Data-Structures#25]
## Write a program to find the size of the binary tree.

This **issue** is open for all, so everyone can work on this issue and every valid **pull request** will be merged.
Maximum number of people can work on this issue, there is no limitations.

### 👨🏻‍💻 Happy Coding 👩🏻‍💻

**Comment by arynn-gupta** [comment]
Would definitely like to work on this issue !

**Comment by GauravPatil8778** [comment]
i have added the program 
check pr #149

**Comment by arynn-gupta** [comment]
Given solution in C++ . Pease merge  https://github.com/C0D1NG/Data-Structures/pull/74
