### ISSUE TITLE
Maximum in Binary Tree

### ISSUE THREAD

**Issue by G1Joshi** [C0D1NG/Data-Structures#27]
## Write a program to find the maximum in binary tree.

This **issue** is open for all, so everyone can work on this issue and every valid **pull request** will be merged.
Maximum number of people can work on this issue, there is no limitations.

### 👨🏻‍💻 Happy Coding 👩🏻‍💻

**Comment by viggi-v** [comment]
Are users required to comment here before making a pr

**Comment by HANS-2002** [comment]
@G1Joshi Please review #281 and merge if suitable.
