### ISSUE TITLE
Identical Trees

### ISSUE THREAD

**Issue by G1Joshi** [C0D1NG/Data-Structures#28]
## Write a program to check whether two tree are identical or not.

This **issue** is open for all, so everyone can work on this issue and every valid **pull request** will be merged.
Maximum number of people can work on this issue, there is no limitations.

### 👨🏻‍💻 Happy Coding 👩🏻‍💻

**Comment by HRITWIKESH** [comment]
hey can i work on this?

**Comment by passionlord** [comment]
this code is interesting i'm looking forward to work more on this
