### ISSUE TITLE
Sum of Nodes in Binary Tree

### ISSUE THREAD

**Issue by G1Joshi** [C0D1NG/Data-Structures#29]
## Write a program to find the sum of nodes of the binary tree.

This **issue** is open for all, so everyone can work on this issue and every valid **pull request** will be merged.
Maximum number of people can work on this issue, there is no limitations.

### 👨🏻‍💻 Happy Coding 👩🏻‍💻

**Comment by Bijoy-007** [comment]
Hi I'll do this

**Comment by Bijoy-007** [comment]
please assign this to me

**Comment by singhalpranav22** [comment]
I am a good competitive programmer assign it to me

**Comment by RaghavKaushal03** [comment]
I have made a pull request

**Comment by devmohit-live** [comment]
@G1Joshi I Have Made a pull request kindly review it

**Comment by HANS-2002** [comment]
@G1Joshi Please review #280 and merge if suitable.
