### ISSUE TITLE
Reverse a Linked List

### ISSUE THREAD

**Issue by G1Joshi** [C0D1NG/Data-Structures#6]
## Write a program to reverse a linked list.

This **issue** is open for all, so everyone can work on this issue and every valid **pull request** will be merged.
Maximum number of people can work on this issue, there is no limitations.

### 👨🏻‍💻 Happy Coding 👩🏻‍💻

**Comment by AkshadK7** [comment]
Can I be assigned this issue for a HacktoberFest PR ?

**Comment by chicken-biryani** [comment]
I have worked on this issue, language-python

**Comment by UtkarshGoel22** [comment]
I have worked on this issue, language-c++14.

**Comment by thecoderash** [comment]
@G1Joshi Please review my PR #298 and consider merging it.
