### ISSUE TITLE
Middle of the Linked List

### ISSUE THREAD

**Issue by G1Joshi** [C0D1NG/Data-Structures#7]
## Write a program to find the middle of the linked list.

This **issue** is open for all, so everyone can work on this issue and every valid **pull request** will be merged.
Maximum number of people can work on this issue, there is no limitations.

### 👨🏻‍💻 Happy Coding 👩🏻‍💻

**Comment by HariniJeyaraman** [comment]
Would like to work on this issue

**Comment by UtkarshGoel22** [comment]
Hi, I would like to work on this issue using c++ language.

**Comment by Rit7knight** [comment]
I would love to work on this
