### ISSUE TITLE
kth Node from end of the Linked List

### ISSUE THREAD

**Issue by G1Joshi** [C0D1NG/Data-Structures#8]
## Write a program to find kth node from end of the linked list.

This **issue** is open for all, so everyone can work on this issue and every valid **pull request** will be merged.
Maximum number of people can work on this issue, there is no limitations.

### 👨🏻‍💻 Happy Coding 👩🏻‍💻

**Comment by HariniJeyaraman** [comment]
Can I work on this for Hacktoberfest ? Please assign this issue to me

**Comment by RaghavKaushal03** [comment]
I can work on this issue in c language

**Comment by yashica-patodia** [comment]
I want to work on this issue @G1Joshi

**Comment by devmohit-live** [comment]
@G1Joshi I Have Made a pull request kindly review it
