### ISSUE TITLE
Palindrome Linked List

### ISSUE THREAD

**Issue by G1Joshi** [C0D1NG/Data-Structures#9]
## Write a program to check whether linked list is palindrome or not.

This **issue** is open for all, so everyone can work on this issue and every valid **pull request** will be merged.
Maximum number of people can work on this issue, there is no limitations.

### 👨🏻‍💻 Happy Coding 👩🏻‍💻

**Comment by arynn-gupta** [comment]
Would definitely like to work on this issue !

**Comment by KshitijDarekar** [comment]
Hi @G1Joshi   , I would like to contribute to this ( by Stack using Linked List ).

**Comment by arynn-gupta** [comment]
Given solution in C++ . Pease merge https://github.com/C0D1NG/Data-Structures/pull/69

**Comment by passionlord** [comment]
added linkedlist program in c please merge #194

**Comment by thecoderash** [comment]
@G1Joshi please consider looking at my PR #299 and consider merging it
